### ISSUE TITLE
Registration checklist

### ISSUE THREAD

**Issue by anowacki** [anowacki/Geodesics.jl#8]
These are a list of things that will need to be done to register the package:

- [ ] Add an API to allow the user to choose the computation algorithm.  Default to `Karney` (GeographicLib).  Include `Vincenty` as an option.  (Maybe add `Haversine` for when using a sphere?)
- [ ] Copy in the code (functionality and tests) of [GeographicLib.jl](https://github.com/anowacki/GeographicLib.jl) to provide the default algorithm, but don't expose the interface.
- [ ] OR: Register GeographicLib.jl as is, and depend on that.
- [ ] Change the name (#3)
- [ ] Bump the minor version
